services:
  hy3d:
    build: .
    container_name: hy3d
    user: "${UID}:${GID}"
    ports:
      - "${GRADIO_SERVER_PORT:-7860}:${GRADIO_SERVER_PORT:-7860}"
    volumes:
      - ./Hunyuan3D-2.1-DGX:/workspace/Hunyuan3D-2.1-DGX
      - ./hy3dpaint/ckpt:/workspace/Hunyuan3D-2.1-DGX/hy3dpaint/ckpt
      - ./hf_cache:/workspace/cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

      HF_HOME: /workspace/cache/huggingface
    env_file:
      - .env
    working_dir: /workspace/Hunyuan3D-2.1-DGX
    tty: true
    stdin_open: true